apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: flask-react-mongo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: <anastasijaangelkoska>/backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_DEBUG
          value: "1"
        - name: MONGO_URI
          value: mongodb://admin:secretpassword@mongo:27017/user_management?authSource=admin
        volumeMounts:
        - name: backend-code
          mountPath: /app
      volumes:
      - name: backend-code
        hostPath:
          path: ./backend
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: flask-react-mongo-app
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: backend
