apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
  namespace: flask-react-mongo-app
data:
  default.conf: |
    server {
      listen 80;
      server_name localhost;

      root /usr/share/nginx/html;
      index index.html;

      # Serve React app for all paths except /api and /mongo
      location / {
        try_files $uri /index.html;
      }

      # Proxy /api requests to backend
      location /api {
        proxy_pass http://backend:5000;
      }

      # Proxy /mongo requests to Mongo Express
      location /mongo {
        proxy_pass http://mongo-express:8081;
      }
    }
